version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
